"""Generation package for LLM synthesis and prompts."""
from src.generation.prompts import (
    GROUNDING_RAG_PROMPT,
    VAULT_INVENTORY_PROMPT,
    CONVERSATIONAL_GREETING_PROMPT,
    VAULT_EMPTY_PROMPT,
    QUERY_REFORMULATION_PROMPT,
    QUERY_DECOMPOSITION_PROMPT,
    DOCUMENT_SUMMARY_PROMPT,
    GRAPH_EXTRACTION_PROMPT,
    COMMUNITY_SUMMARY_PROMPT,
    EVAL_FAITHFULNESS_PROMPT,
    EVAL_RELEVANCE_PROMPT,
)
from src.generation.llm import (
    invoke_groq_with_fallback,
    stream_groq_with_fallback,
    resolve_model_name,
    DEFAULT_MODELS,
    MODEL_ALIASES,
)
from src.generation.service import (
    reformulate_query,
    decompose_query,
    is_vault_meta_query,
    is_conversational_query,
    prepare_context_and_prompt,
    answer_query_stream,
    answer_query,
)

__all__ = [
    "GROUNDING_RAG_PROMPT",
    "VAULT_INVENTORY_PROMPT",
    "CONVERSATIONAL_GREETING_PROMPT",
    "VAULT_EMPTY_PROMPT",
    "QUERY_REFORMULATION_PROMPT",
    "QUERY_DECOMPOSITION_PROMPT",
    "DOCUMENT_SUMMARY_PROMPT",
    "GRAPH_EXTRACTION_PROMPT",
    "COMMUNITY_SUMMARY_PROMPT",
    "EVAL_FAITHFULNESS_PROMPT",
    "EVAL_RELEVANCE_PROMPT",
    "invoke_groq_with_fallback",
    "stream_groq_with_fallback",
    "resolve_model_name",
    "DEFAULT_MODELS",
    "MODEL_ALIASES",
    "reformulate_query",
    "decompose_query",
    "is_vault_meta_query",
    "is_conversational_query",
    "prepare_context_and_prompt",
    "answer_query_stream",
    "answer_query",
]
