"""Storage package for vector, relational, and file storage."""
from src.storage.vector_store import (
    get_qdrant_client,
    init_db,
    ensure_payload_indices,
    clear_collection,
    delete_files_from_collection,
    delete_file_from_collection,
    delete_user_vectors,
    get_collection_stats,
    invalidate_stats_cache,
)
from src.storage.chat_db import (
    init_chat_db,
    create_session,
    get_all_sessions,
    add_message,
    save_message_async,
    get_session_messages,
    delete_session,
    delete_user_sessions,
)
from src.storage.docs_db import (
    init_docs_db,
    upsert_document_record,
    update_document_status,
    get_user_documents,
    delete_document_records,
    delete_document_record,
)
from src.storage.file_storage import (
    get_user_uploads_dir,
    resolve_document_path,
    upload_file,
    upload_bytes,
    download_file,
    download_bytes,
    delete_file,
    list_files,
    get_user_files,
    delete_physical_document,
)

__all__ = [
    "get_qdrant_client",
    "init_db",
    "ensure_payload_indices",
    "clear_collection",
    "delete_files_from_collection",
    "delete_file_from_collection",
    "delete_user_vectors",
    "get_collection_stats",
    "invalidate_stats_cache",
    "init_chat_db",
    "create_session",
    "get_all_sessions",
    "add_message",
    "save_message_async",
    "get_session_messages",
    "delete_session",
    "delete_user_sessions",
    "init_docs_db",
    "upsert_document_record",
    "update_document_status",
    "get_user_documents",
    "delete_document_records",
    "delete_document_record",
    "get_user_uploads_dir",
    "resolve_document_path",
    "upload_file",
    "upload_bytes",
    "download_file",
    "download_bytes",
    "delete_file",
    "list_files",
    "get_user_files",
    "delete_physical_document",
]
